before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
dockers:
  - image_templates:
      - ghcr.io/syoi-org/syoi-access:{{.Tag}}
      - ghcr.io/syoi-org/syoi-access:v{{.Major}}
      - ghcr.io/syoi-org/syoi-access:v{{.Major}}.{{.Minor}}
      - ghcr.io/syoi-org/syoi-access:latest
    use: buildx
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
